#! /usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "aws-sdk"
require "fileutils"
require 'trollop'

  opts = Trollop::options do
    opt :file, "", :type => :string 
    opt :stack, "", :type => :string
  end
Trollop::die :file, "represent a file to write to" unless opts[:file]
Trollop::die :stack, "represent a stack on aws" unless opts[:stack]

puts opts
cfm = AWS::CloudFormation.new
stack = cfm.stacks[opts[:stack]]
filename = opts[:file]

 if File.exists?(filename)
 	old_filename = "#{filename}.#{Time.now.to_i.to_s}"
	FileUtils.mv(filename, old_filename)
	puts "old cloudformation: #{old_filename}"
end
File.open(filename, mode= "w+"){|file| file.write(stack.template) }
puts filename