#! /usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "fog"
require "fileutils"
require 'trollop'
require 'yaml'

require_relative 'environment.rb'
include Environment

opts = Trollop::options do
	opt :environment, "", :type => :string
end	
Trollop::die :environment, "needs an environment. Valid values(#{environments.keys.join(',')})" unless environments.keys.include? opts[:environment]


settings = set_environment(opts[:environment])

@connection = Fog::Compute::AWS.new(settings)
@connection.servers.each do |instance| 
		puts "#{instance.id}, #{instance.tags['Name']}, #{instance.availability_zone} "
	end