#! /usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "fog"
require "fileutils"
require 'trollop'
require 'yaml'

require_relative 'environment.rb'
require_relative 'ssh_instance.rb'
require_relative 'menu.rb'

include Environment
include Menu



opts = Trollop::options do
	opt :environment, "", :type => :string
	opt :regex, "", :type => :string
end	

environment = opts[:environment] || get_environment
regex = opts[:regex]
settings = set_environment(environment)

instance = SshInstance.get(environment, settings, regex)

instance.login

