#! /usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "fog"
require "fileutils"
require 'trollop'
require 'yaml'

require_relative 'environment.rb'
require_relative 'menu.rb'
require_relative 'ssh_instance.rb'
require_relative 'scp_instance.rb'
include Environment
include Menu

SUB_COMMANDS = %w(get put)
opts = Trollop::options do
	opt :environment, "", :type => :string, :default => ""
  opt :regex, "", :type => :string
	stop_on SUB_COMMANDS
end	

cmd = ARGV.shift # get the subcommand
cmd_opts = case cmd
  when "get" # parse delete options
    Trollop::options do
      opt :get, "get the file", :default => true
    end
  when "put"  # parse copy options
    Trollop::options do
      opt :put, "puts the file", :default => true
    end
  else
    Trollop::die "unknown subcommand #{cmd.inspect}"
  end


environment = opts[:environment] || get_environment
settings = set_environment(environment)
regex = opts[:regex]

instances = ScpInstance.all(environment, settings, regex)
  remote_path = get_path('remote')
  local_path = get_path('local')
instances.each do |instance|
  instance.remote_path = remote_path
  instance.local_path = local_path
  ssh_cmd = instance.get_cmd if !cmd_opts[:get].nil?
  ssh_cmd = instance.put_cmd if !cmd_opts[:put].nil?
  puts ssh_cmd
  `#{ssh_cmd}`
end  