#! /usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "fog"
require "fileutils"
require 'trollop'
require 'yaml'

require_relative 'environment.rb'
include Environment

opts = Trollop::options do
	opt :instance, "", :type => :string
end	
Trollop::die :instance, "needs an instance id" unless opts[:instance]

environments.each do |key, settings|
@connection = Fog::Compute::AWS.new(settings)
	instance = 	@connection.servers.get(opts[:instance])
	unless instance.nil?
		puts "#{key} #{instance.tags['Name']}"
		exit
	end
end
